### ISSUE TITLE
Text is hard to see in Tango theme when using dark mode.

### ISSUE THREAD

**Issue by cwchristerw** [linuxmint/xed#572]
```
xed - Version 3.2.8
Linux Mint 21.1
```

**Issue**
Editing yaml file in xed and using dark mode, `---` and `\"` is too dark in dark mode.

**Steps to reproduce**
1. Create file in light mode
```
---
- name: "Workstations : Fonts : Download - Akashi"
  get_url:
    url: "https://example.com/files/Akashi.ttf"
    dest: "~/.local/share/fonts/{{ \"https://example.com/files/Akashi.ttf\" | urlsplit('path') | basename }}"
  become: true
  become_user: "{{ user }}"
  loop: "{{ users }}"
  loop_control:
    label: "{{ user }}"
    loop_var: "user"
  vars:
    users:
      - root
      - user
```
2. Go to Edit > Preferences > Theme and enable Dark Mode and select Tango theme.

**Expected behaviour**
Text is light enough when using dark mode. Other themes are working correctly.

**Other information**
